export const MESSAGES = {
  MOCK_ADDED: "Mock added successfully",
  MOCK_UPDATED: "Mock updated successfully",
  MOCK_UPDATED_FAILED: "There is nothing to change",
  MOCK_SAVE_FAILED: "Failed to save mock",
  MOCK_UNKNOWN: "Unknown",
  URL_REQUIRED: "Please enter URL",
  RESPONSE_REQUIRED: "Please enter mock response",
  URL_INVALID: "Please enter a valid URL",
  RESPONSE_INVALID: "Please enter a valid JSON response",
  MOCK_EXIST: "A mock with this URL already exists!",
  EDIT_MOCK_EXIST: "Another mock is already using this URL!",
  SUCCESS_EXPORT: "Mocks exported successfully",
  FAILED_EXPORT: "Failed to export mocks",
  SUCCESS_IMPORT: "Mocks imported successfully",
  FAILED_IMPORT: "Failed to import mocks",
  FAILED_INVALID_IMPORT: "Failed to import: Invalid file format",
  MESSAGE_DUPLICATE_MOCK: "At least one similar mock already exists.",
} as const;
